# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-23 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='filename',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='level',
            field=models.IntegerField(choices=[(100, 'Debug'), (200, 'Info'), (300, 'Warning'), (400, 'Critical')], null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='lineno',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='reason',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
