# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-23 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20170623_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='text',
            new_name='message',
        ),
    ]
