# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-24 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_auto_20170623_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='level',
            field=models.IntegerField(choices=[(0, 'Debug'), (100, 'Info'), (200, 'Success'), (300, 'Warning'), (400, 'Critical'), (500, 'Fatal')], null=True),
        ),
    ]
